name: Assessment Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install --with-deps chromium
    
    - name: Setup directories
      run: |
        mkdir -p reports
        mkdir -p downloads
        mkdir -p logs
        chmod -R 777 reports downloads logs
    
    - name: Install local package
      run: |
        pip install -e .
    
    - name: Run Test
      env:
        PYTHONPATH: ${{ github.workspace }}
        PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/ms-playwright
      run: |
        python -m pytest tests/test_end_to_end_purchase.py -v --html=reports/report.html --capture=no
    
    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: |
          reports/
          downloads/
          logs/
        retention-days: 30