name: Assessment Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-playwright
        playwright install --with-deps chromium
        playwright install-deps chromium

    - name: Create Directories
      run: |
        mkdir -p reports
        mkdir -p downloads
        mkdir -p logs

    - name: Run Tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        python -m pytest tests/test_end_to_end_purchase.py -v --html=reports/report.html --self-contained-html

    - name: Upload HTML Test Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: reports/report.html
        retention-days: 30

    - name: Upload Failed Test Screenshots
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-failures
        path: |
          **/screenshots/*.png
          **/test-results/
        retention-days: 7

    - name: Upload Invoice
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: invoice
        path: downloads/invoice_invoice.txt
        retention-days: 30