name: Assessment Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox]
      fail-fast: false
      max-parallel: 2

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-playwright
        python -m playwright install --with-deps ${{ matrix.browser }}

    - name: Create Directories
      run: |
        mkdir -p reports/${{ matrix.browser }}
        mkdir -p downloads/${{ matrix.browser }}
        mkdir -p logs/${{ matrix.browser }}

    - name: Run Tests
      env:
        PYTHONPATH: ${{ github.workspace }}
        BROWSER: ${{ matrix.browser }}
        DOWNLOAD_PATH: ${{ github.workspace }}/downloads/${{ matrix.browser }}
      run: |
        python -m pytest tests/test_end_to_end_purchase.py tests/test_api_create_account.py -v --html=reports/${{ matrix.browser }}/report.html --self-contained-html

    - name: Upload Test Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.browser }}
        path: |
          reports/${{ matrix.browser }}
          downloads/${{ matrix.browser }}
          logs/${{ matrix.browser }}
        retention-days: 30

    - name: Upload Failed Test Screenshots
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-failures-${{ matrix.browser }}
        path: |
          **/screenshots/*.png
          **/test-results/
        retention-days: 7