name: Python Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        browser: ["chromium", "firefox"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r automation/requirements.txt
          python -m playwright install ${{ matrix.browser }}

      - name: Run tests
        env:
          BROWSERS: ${{ matrix.browser }}
        run: |
          cd automation
          pytest -v -s --junitxml=test-results-${{ matrix.browser }}.xml

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.browser }}
          path: automation/test-results-${{ matrix.browser }}.xml
