name: Assessment Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2 libatk1.0-0 libatk-bridge2.0-0 libcairo2 libcups2 \
          libgdk-pixbuf2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libx11-6 libx11-xcb1 libxcb1 \
          libxcomposite1 libxdamage1 libxext6 libxfixes3 libxrandr2 xvfb \
          libnss3 libxss1 libcairo-gobject2 libpangocairo-1.0-0

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        
    - name: Install browsers
      run: |
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=0 playwright install --with-deps chromium firefox
    
    - name: Setup directories
      run: |
        mkdir -p reports downloads logs
        chmod -R 777 reports downloads logs
    
    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        python -m pytest tests/test_end_to_end_purchase.py -v --html=reports/report.html
    
    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          reports/
          downloads/
          logs/
        retention-days: 30